name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npx eslint .

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Unit Tests
        run: npm test

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build

  deployment:
    runs-on: ubuntu-latest
    needs: [linting, unit_tests, build-and-test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deployment
        run: ./deploy.sh

